server:
  port: ${acp_server_port:0}
  undertow:
    threads:
      worker: 1000
spring:
  profiles:
    active: ${acp_profile_active:dev}
  application:
    name: route-server
  thymeleaf:
    cache: false
  #  zipkin:
  #    sender:
  #      type: kafka
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      username: ${acp_nacos_username:nacos}
      password: ${acp_nacos_password:nacos}
      server-addr: ${acp_nacos_addr:127.0.0.1:8848}
      discovery:
        namespace: ${acp_nacos_namespace:acp-cloud-admin}
        cluster-name: ${spring.profiles.active}
        group: ${spring.profiles.active}
      config:
        namespace: ${spring.cloud.nacos.discovery.namespace}
        cluster-name: ${spring.cloud.nacos.discovery.cluster-name}
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=${spring.cloud.nacos.discovery.group}
      - optional:nacos:atom-server-common-${spring.profiles.active}.yaml?group=${spring.cloud.nacos.discovery.group}
logging:
  file:
    path: ${acp_log_path:logs}/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
info:
  version: 5.1.4
  app-name: ${spring.application.name}
  tags:
    environment: ${spring.profiles.active}
  build:
    author: zhangbin
    active: ${spring.profiles.active}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    env:
      enabled: true
knife4j:
  enable: true
acp:
  cloud:
    log-server:
      client:
        enabled: true
        log-type: ROUTE