server:
  port: ${acp_server_port:8771}
  undertow:
    threads:
      worker: 1000
spring:
  profiles:
    active: ${acp_profile_active:dev}
  application:
    name: gateway-server
  thymeleaf:
    cache: false
  cloud:
    nacos:
      username: ${acp_nacos_username:nacos}
      password: ${acp_nacos_password:nacos}
      server-addr: ${acp_nacos_addr:127.0.0.1:8848}
      discovery:
        namespace: ${acp_nacos_namespace:acp-cloud-admin}
        cluster-name: ${spring.profiles.active}
        group: ${spring.profiles.active}
      config:
        namespace: ${spring.cloud.nacos.discovery.namespace}
        cluster-name: ${spring.cloud.nacos.discovery.cluster-name}
    # ===============================
    # = GateWay Config
    # ===============================
    gateway:
      loadbalancer:
        use404: true
      routes:
        - id: deploy-server-api
          uri: lb://deploy-server
          predicates:
            - Path=/api/deploy/**
          filters:
            - StripPrefix=1
        - id: log-server-api
          uri: lb://log-server
          predicates:
            - Path=/api/log/**
          filters:
            - StripPrefix=1
        - id: route-server-api
          uri: lb://route-server
          predicates:
            - Path=/api/route/**
          filters:
            - StripPrefix=1
        - id: oauth2-server-api
          uri: lb://oauth2-server
          predicates:
            - Path=/api/oauth/**
          filters:
            - StripPrefix=1
        - id: oauth2-server-open
          uri: lb://oauth2-server
          predicates:
            - Path=/open/oauth/**
          filters:
            - RewritePath=/open/oauth/(?<segment>.*),/open/$\{segment}
  #            - name: RequestRateLimiter
  #              args:
  #                redis-rate-limiter.replenishRate: 10
  #                redis-rate-limiter.burstCapacity: 20
  #                rate-limiter: "#{@myRateLimiter}"
  #                key-resolver: "#{@userKeyResolver}"
  config:
    import:
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yaml?group=${spring.cloud.nacos.discovery.group}
      - optional:nacos:atom-server-common-${spring.profiles.active}.yaml?group=${spring.cloud.nacos.discovery.group}
logging:
  file:
    path: ${acp_log_path:logs}/${spring.application.name}
    name: ${logging.file.path}/${spring.application.name}.log
  pattern:
    file: '[%date{yyyy-MM-dd HH:mm:ss.SSS}] [ %-5level] [%thread] %logger{96} [%X{lineno}] - %msg%n'
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30
  level:
    com.alibaba.nacos.client: warn
    org.springframework.cloud.function: warn
info:
  version: 5.1.3
  app-name: ${spring.application.name}
  tags:
    environment: ${spring.profiles.active}
  build:
    author: zhangbin
    active: ${spring.profiles.active}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  info:
    java:
      enabled: true
    env:
      enabled: true