package pers.acp.admin.constant

/**
 * @author zhang by 15/01/2019
 * @since JDK 11
 */
object ModuleFuncCode {
    const val other = "other"
    const val sysMonitor = "sys_monitor"
    const val sysConfig = "sys_config"
    const val runtimeConfig = "runtime_config"
    const val runtimeAdd = "runtime_add"
    const val runtimeDelete = "runtime_delete"
    const val runtimeUpdate = "runtime_update"
    const val runtimeQuery = "runtime_query"
    const val appConfig = "app_config"
    const val appAdd = "app_add"
    const val appDelete = "app_delete"
    const val appUpdate = "app_update"
    const val appQuery = "app_query"
    const val appUpdateSecret = "app_update_secret"
    const val orgConfig = "org_config"
    const val orgAdd = "org_add"
    const val orgDelete = "org_delete"
    const val orgUpdate = "org_update"
    const val orgQuery = "org_query"
    const val roleConfig = "role_config"
    const val roleAdd = "role_add"
    const val roleDelete = "role_delete"
    const val roleUpdate = "role_update"
    const val roleQuery = "role_query"
    const val authConfig = "auth_config"
    const val authAdd = "auth_add"
    const val authDelete = "auth_delete"
    const val authUpdate = "auth_update"
    const val authQuery = "auth_query"
    const val userConfig = "user_config"
    const val userAdd = "user_add"
    const val userDelete = "user_delete"
    const val userUpdate = "user_update"
    const val userQuery = "user_query"
    const val flowManage = "flow_manage"
    const val flowAdmin = "flow_admin"
    const val flowDefinition = "flow_definition"
    const val flowPending = "flow_pending"
    const val flowProcess = "flow_process"
}